var GAME_LEVELS = [
  [" x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                          x   ",
   " x                                                                           x  ",
   " x                                                                           x  ",
   " x                                                                            x ",
   " x                                       xxxxx                                x ",
   " x                                                                            x ",
   " x  @                                                          xxxxx          x ",
   " xxxxxxxxxxxxx     xxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxx   xxxxxxxxxx x ",
   "             x     x          x   x                  x     x                xox ",
   "             xxxxxxx          x!!!x                  x!!!!!x                x x ",
   "                              x!!!x                  x!!!!!x                x x ",
   "                              xxxxx                  xxxxxxx                x x ",
   "                                                                            x x ",
   "                                                                            x x "],
  [" x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x   @                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x                                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " x                                                                                       xxxxx",
   " x                                                                                       xxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                  xxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        xxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxx",
   " x                                          v    v  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxx",
   " x                                                                                       xxxxx",
   " x                                                                                       xxxxx",
   " x                                                                                       xxxxx",
   " x     o                                                                                 xxxxx",
   " x                                                                                       xxxxx",
   " xxxxxxxx                                                                                xxxxx",
   " xxxxxxxx                                 xxxxxxxxxxx                                    xxxxx",
   " xxxxxxxx   xxxxx      xxxxx     xxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxx!!!xxxxx!!!!!!xxxxx!!!!!xxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxx!!!xxxxx!!!!!!xxxxx!!!!!xxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxx!!!xxxxx!!!!!!xxxxx!!!!!xxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxx!!!xxxxx!!!!!!xxxxx!!!!!xxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxx!!!xxxxx!!!!!!xxxxx!!!!!xxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    !!!!!!!       !!!!!!!!!!!!!!                             !!!!!!                 !!!!!!               ",
   "      v !!!        !!!!!!!!!!!v                               v !v!                   !!v!               ",
   "         v             !v!! !                                 v  v                       v               ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   " @                                                                                                       ",
   "                                                                                                         ",
   "xxxx                  xxx                                                                                ",
   "xxxx             xx   xxx                                                                                ",
   "xxxx      xxx    xx   xxx                                                                              o ",
   "xxxx      xxx    xx   xxx                                                                                ",
   "xxxx      xxx    xx   xxx       xxxxxxxxx                                                        xxxxxxxx",
   "xxxx      xxx    xx   xxx       xxxxxxxxx                                                xxx     xxxxxxxx",
   "xxxx      xxx    xx   xxx       xxxxxxxxx                                         xxx    xxx     xxxxxxxx",
   "xxxx      xxx    xx   xxx       xxxxxxxxx        xxxxxxxxxx                 xx    xxx    xxx     xxxxxxxx",
   "xxxx!!!!!!xxx!!!!xx!!!xxx!!!!!!!xxxxxxxxx!!!!!!!!xxxxxxxxxx!!!!!xxxxxxx!!!!!xx!!!!xxx!!!!xxx!!!!!xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!!!!!!!!!!vv!",
   "  vv!!!!!!vv    !!!!!!    vv!!!!!!vv    !!!!!!    vv!!!!!!vv    !!!!!!    vv!!!!!!vv    !!!!!!    vv!!!!!!vv   ",
   "      !!        vv!!vv        !!        vv!!vv        !!        vv!!vv        !!        vv!!vv        !!       ",
   "      vv          vv          vv          vv          vv          vv          vv          vv          vv       ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                       xxxxxxxxxxxxxx                                          ",
   "                                                                                                               ",
   "                                       xxxxxxxxx                                            xxxx               ",
   "                                                                                                               ",
   "            xxxxxxxxx                                  xxxxxxxxxxxxxx                                          ",
   "                                         xxxxxx        !v!!v!!v!!v!!!                                          ",
   "                                         xxxxxx                                             xxxx               ",
   "              xxxxx                      xxxxxx                             xxxxxx        xxxxxx               ",
   "  @           xxxxx                      xxxxxx                             xxxxxx       xxxxxxx           o   ",
   "              xxxxx         xxxxxxx      xxxxxx                             xxxxxx     xxxxxxxxx               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["      xx      xx     xxxxx      xx       xx           xx          xx     xxxxxx     xx       xx               ",
   "       xx    xx    xx     xx    xx       xx           xx          xx   xx      xx   xxxx     xx               ",
   "       xx    xx   xx       xx   xx       xx           xx          xx  xx        xx  xx xx    xx               ",
   "        xxxxxx    xx       xx   xx       xx           xx    xx    xx  xx        xx  xx  xx   xx               ",
   "          xx      xx       xx   xx       xx           xx    xx    xx  xx        xx  xx   xx  xx               ",
   "          xx       xx     xx    xx       xx           xx    xx    xx   xx      xx   xx    xx xx               ",
   "  @       xx         xxxxx       xxxxxxxxx             xxxxxxxxxxxxx     xxxxxx     xx     xxxx               ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
